# Generated by Django 2.0.1 on 2018-02-24 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apkname', models.CharField(max_length=64, unique=True, verbose_name='包名')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='应用名')),
                ('publisher', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='发行商')),
                ('icon', models.ImageField(blank=True, default='static/app/icon/icon_default.jpeg', null=True, upload_to='static/app/icon/', verbose_name='图标')),
            ],
        ),
        migrations.CreateModel(
            name='AppCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='分类名')),
                ('app', models.ForeignKey(on_delete=False, to='account.App', verbose_name='所属应用')),
            ],
        ),
        migrations.CreateModel(
            name='AppDownloadLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.URLField(verbose_name='下载链接')),
                ('app', models.ForeignKey(on_delete=False, to='account.App', verbose_name='所属应用')),
            ],
        ),
        migrations.CreateModel(
            name='AppID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_identify', models.CharField(max_length=64, verbose_name='应用ID')),
                ('app', models.ForeignKey(on_delete=False, to='account.App', verbose_name='所属应用')),
            ],
        ),
        migrations.CreateModel(
            name='AppRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='排名')),
                ('date', models.DateField(verbose_name='日期')),
                ('span', models.IntegerField(blank=True, choices=[(1, '天'), (7, '周'), (30, '月'), (90, '季度'), (180, '半年'), (365, '年度')], null=True, verbose_name='排名')),
                ('app', models.ForeignKey(on_delete=False, to='account.App', verbose_name='所属应用')),
            ],
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='版本名')),
                ('date', models.DateField(verbose_name='发布日期')),
                ('app', models.ForeignKey(on_delete=False, to='account.App', verbose_name='所属应用')),
            ],
        ),
        migrations.CreateModel(
            name='Downloads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily', models.IntegerField(blank=True, null=True, verbose_name='日下载量')),
                ('subtotal', models.IntegerField(blank=True, null=True, verbose_name='日累计总量')),
                ('date', models.DateField(verbose_name='日期')),
                ('app', models.ForeignKey(on_delete=False, to='account.App', verbose_name='所属应用')),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='应用市场名')),
                ('href', models.URLField(verbose_name='官网链接')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='static/avatar/avatar_default.jpeg', null=True, upload_to='static/avatar/', verbose_name='头像')),
                ('nickname', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='昵称')),
                ('telephone', models.CharField(max_length=32, unique=True, verbose_name='手机号码')),
                ('user', models.OneToOneField(on_delete=False, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.AddField(
            model_name='downloads',
            name='market',
            field=models.ForeignKey(on_delete=False, to='account.Market', verbose_name='所属市场'),
        ),
        migrations.AddField(
            model_name='appversion',
            name='market',
            field=models.ForeignKey(on_delete=False, to='account.Market', verbose_name='所属市场'),
        ),
        migrations.AddField(
            model_name='apprank',
            name='market',
            field=models.ForeignKey(on_delete=False, to='account.Market', verbose_name='所属市场'),
        ),
        migrations.AddField(
            model_name='appid',
            name='market',
            field=models.ForeignKey(on_delete=False, to='account.Market', verbose_name='所属市场'),
        ),
        migrations.AddField(
            model_name='appdownloadlink',
            name='market',
            field=models.ForeignKey(on_delete=False, to='account.Market', verbose_name='所属市场'),
        ),
        migrations.AddField(
            model_name='appcategory',
            name='market',
            field=models.ForeignKey(on_delete=False, to='account.Market', verbose_name='所属市场'),
        ),
    ]
